services:
  - type: web
    name: palmguard-python
    runtime: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "8000"
      - key: MEDIAPIPE_DISABLE_GPU
        value: "1"
      - key: DISPLAY
        value: ""
      - key: LIBGL_ALWAYS_SOFTWARE
        value: "1"
